### ISSUE TITLE
Spike on publishing options

### ISSUE THREAD

**Issue by kmcelwee** [kmcelwee/fortune-100-blm-report#2]
Isn't combining markdown with charts what Jupyter was made for? But I want a friendlier medium to any reader... so a proper website? I don't want to invest so much time in that! I could generate a website from Markdown which points to the files generated here. The only concern is interactive graphs, but D3 has certainly been used in GitHub pages elsewhere.

**Comment by gusbemacbe** [comment]
@kmcelwee, do you mean https://github.com/fastai/fastpages? I am interested in your post you successfully solved.

**Comment by kmcelwee** [comment]
@gusbemacbe I ended up writing custom HTML/CSS/JS for this site, I didn't end up using fast pages.
